# Generated by Django 2.1.5 on 2019-03-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FG', 'FoodGiver'), ('FT', 'FoodTaker'), ('AD', 'Admin')], default='FoodGiver', max_length=2),
        ),
    ]
