# Generated by Django 2.1.5 on 2019-03-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190312_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FoodGiver', 'FoodGiver'), ('FoodTaker', 'FoodTaker'), ('Admin', 'Admin')], default='FoodGiver', max_length=12),
        ),
    ]
