# Generated by Django 2.1.5 on 2019-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190314_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='requested_by',
            field=models.IntegerField(default=None),
        ),
    ]
