# Generated by Django 2.1.5 on 2019-03-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190315_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='requested_by',
            field=models.IntegerField(default=0),
        ),
    ]
