# Generated by Django 2.1.5 on 2019-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190318_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='role',
            field=models.CharField(choices=[('FoodGiver', 'FoodGiver'), ('FoodTaker', 'FoodTaker')], default='FoodGiver', max_length=12),
        ),
    ]
