# Generated by Django 2.1.7 on 2019-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190319_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='available_time',
            field=models.TimeField(default='12:00AM', verbose_name='pickup time'),
            preserve_default=False,
        ),
    ]
