# Generated by Django 2.1.7 on 2019-03-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_meal_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='available_time',
        ),
    ]
