# Generated by Django 2.1.7 on 2019-03-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_meal_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='available_time',
        ),
    ]
