# Generated by Django 2.1.7 on 2019-03-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_meal_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='available_time',
            field=models.TimeField(verbose_name='pickup time'),
        ),
    ]
